# Travis CI Configuration
# https://docs.travis-ci.com

language: svg

## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

git:
  depth: 30

addons:
  apt:
    packages:
      - realpath      # Merged to GNU Coreutils in Ubuntu 16.04
      - inkscape
      - p7zip
      - xmlstarlet
      - cabal-install # for ShellCheck
      - ghc # for ShellCheck

install:
  # For GNU Bash script checking
  - ./"開發工具/Utilities for Travis CI/Build and Setup ShellCheck's Latest Release.bash" --without-root
  - PATH=${HOME}/.cabal/bin:${PATH}

  # For fonts used in design
  - ./下載並安裝需要用到的字型.bash

  # For subset font generation
  - pip install --user fonttools
  - pip install --user brotli
  - PATH="${HOME}/.local/bin:${PATH}"

before_script:
  - ./"開發工具/GNU Bash Automatic Checking Program for Git Projects.bash"
  - ./"Travis CI 支援/讓 Fontconfig 認為 Subset OTF 變種的思源黑體也是思源黑體.bash"

script:
  - 軟體建構解決方案/批次命令/build.bash
  - ./"製作子集合 Web 字型.bash"

before_cache:
  - rm --force $HOME/.cabal/logs/build.log

cache:
  pip: true
  directories:
    - ${HOME}/.cabal

before_deploy:
  - cp 建構中間產物/l10n-tw-logo*/* "GitHub Pages 網站/圖片"
  - cp README.markdown "GitHub Pages 網站"
  - cp 字型/SourceHanSerif*-SemiBold.subset.otf 字型/SourceHanSerif*-SemiBold.subset.woff* "GitHub Pages 網站/字型"

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN_HIDDEN
    skip_cleanup: true
    file_glob: true
    file: 
      - 建構結果/l10n-tw-logo-*.7z
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo.svg
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo.png
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo-non-transparent.png
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo-with-metadata.svg
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo-with-metadata.png
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo-with-metadata-non-transparent.svg
    on:
      tags: true
  - provider: pages
    github_token: $GITHUB_ACCESS_TOKEN_HIDDEN
    skip_cleanup: true
    local_dir: "GitHub Pages 網站"
    on:
      branch: 主要開發分支