# Travis CI Configuration
# https://docs.travis-ci.com

language: svg

## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

git:
  depth: 30

addons:
  apt:
    packages:
      - realpath      # Merged to GNU Coreutils in Ubuntu 16.04
      - inkscape
      - p7zip
      - xmlstarlet

install:
  - pip --prefix "${HOME}" install fonttools

script:
  - ./下載並安裝需要用到的字型.bash
  - ./"Travis CI 支援/讓 Fontconfig 認為 Subset OTF 變種的思源黑體也是思源黑體.bash"
  - 軟體建構解決方案/批次命令/build.bash

before_deploy:
  - cp 建構中間產物/l10n-tw-logo*/* "GitHub Pages 網站/圖片"
  - cp README.markdown "GitHub Pages 網站"

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN_HIDDEN
    skip_cleanup: true
    file_glob: true
    file: 
      - 建構結果/l10n-tw-logo-*.7z
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo.svg
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo.png
      - 建構中間產物/l10n-tw-logo*/l10n-tw-logo-non-transparent.png
    on:
      tags: true
  - provider: pages
    github_token: $GITHUB_ACCESS_TOKEN_HIDDEN
    skip_cleanup: true
    local_dir: "GitHub Pages 網站"
    on:
      branch: 主要開發分支